name: Build and Push Docker Images

on:
  push:
    branches:
      - master
    paths:
      - 'app/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Images
        env:
          IMAGE1: node-test-app
          REPOSITORY_TAG1: ${{ secrets.DOCKERHUB_USERNAME }}/node-test-app
          DOCKER_TAG: latest  
        run: |
          docker build -t $REPOSITORY_TAG1:$DOCKER_TAG app/
          docker push $REPOSITORY_TAG1:$DOCKER_TAG
